/** Lumen 主题必须实现的公共 CSS 变量。 */
export const lumenThemeVariables = [
  '--lumen-font-family',
  '--lumen-font-weight-normal',
  '--lumen-font-weight-medium',
  '--lumen-font-weight-strong',
  '--lumen-color-primary',
  '--lumen-color-primary-hover',
  '--lumen-color-primary-active',
  '--lumen-color-primary-soft',
  '--lumen-color-primary-soft-hover',
  '--lumen-color-on-primary',
  '--lumen-color-text-strong',
  '--lumen-color-text',
  '--lumen-color-text-secondary',
  '--lumen-color-text-muted',
  '--lumen-color-text-placeholder',
  '--lumen-color-surface',
  '--lumen-color-surface-muted',
  '--lumen-color-surface-subtle',
  '--lumen-color-surface-hover',
  '--lumen-color-surface-glass',
  '--lumen-color-overlay',
  '--lumen-color-border',
  '--lumen-color-divider',
  '--lumen-color-border-strong',
  '--lumen-color-border-hover',
  '--lumen-color-focus-ring',
  '--lumen-color-danger',
  '--lumen-color-danger-hover',
  '--lumen-color-danger-soft',
  '--lumen-color-danger-border',
  '--lumen-color-danger-text',
  '--lumen-color-success',
  '--lumen-color-success-soft',
  '--lumen-color-success-border',
  '--lumen-color-success-text',
  '--lumen-color-warning',
  '--lumen-color-warning-soft',
  '--lumen-color-warning-border',
  '--lumen-color-warning-text',
  '--lumen-color-rating',
  '--lumen-color-info',
  '--lumen-color-info-soft',
  '--lumen-color-info-border',
  '--lumen-color-info-text',
  '--lumen-color-tooltip',
  '--lumen-color-tooltip-text',
  '--lumen-color-shadow',
  '--lumen-radius-tag',
  '--lumen-radius-control',
  '--lumen-radius-icon',
  '--lumen-radius-card',
  '--lumen-radius-modal',
  '--lumen-radius-pill',
  '--lumen-shadow-control',
  '--lumen-shadow-card',
  '--lumen-shadow-dropdown',
  '--lumen-shadow-modal',
  '--lumen-control-height-sm',
  '--lumen-control-height-md',
  '--lumen-control-height-lg',
  '--lumen-motion-duration-fast',
  '--lumen-motion-duration-normal',
  '--lumen-motion-ease-standard',
  '--lumen-motion-ease-enter',
  '--lumen-motion-ease-exit',
] as const;

export type LumenThemeVariable = (typeof lumenThemeVariables)[number];

export const lumenThemeAttributes = {
  theme: 'data-lumen-theme',
  colorScheme: 'data-color-scheme',
  density: 'data-density',
} as const;
