import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import ts from 'typescript';

const projectRoot = resolve(import.meta.dirname, '..');
const sourcePath = resolve(projectRoot, 'playground/src/App.tsx');
const outputPath = resolve(projectRoot, 'playground/src/generated/demoCardCode.ts');
const apiOutputPath = resolve(projectRoot, 'playground/src/generated/componentApi.ts');
const sourceText = await readFile(sourcePath, 'utf8');
const sourceFile = ts.createSourceFile(
  sourcePath,
  sourceText,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TSX,
);
const examples: Record<string, string> = {};

const normalizeJsx = (source: string) => {
  const lines = source.replace(/^\s*\n|\n\s*$/g, '').split('\n');
  const continuationIndents = lines
    .slice(1)
    .filter((line) => line.trim())
    .map((line) => line.match(/^\s*/)?.[0].length ?? 0);
  const indent = continuationIndents.length ? Math.min(...continuationIndents) : 0;

  return lines
    .map((line, index) => index === 0 ? line.trimStart() : line.slice(indent))
    .join('\n');
};

const visit = (node: ts.Node) => {
  if (ts.isJsxElement(node) && node.openingElement.tagName.getText(sourceFile) === 'DemoCard') {
    const titleAttribute = node.openingElement.attributes.properties.find(
      (attribute) => ts.isJsxAttribute(attribute) && attribute.name.getText(sourceFile) === 'title',
    );
    const title = titleAttribute?.initializer && ts.isStringLiteral(titleAttribute.initializer)
      ? titleAttribute.initializer.text
      : undefined;

    if (!title) throw new Error('Every DemoCard must have a static string title.');
    if (examples[title]) throw new Error(`Duplicate DemoCard title: ${title}`);

    const jsx = normalizeJsx(
      node.children.map((child) => child.getFullText(sourceFile)).join(''),
    );
    const rootChildren = node.children.filter(
      (child) => !ts.isJsxText(child) || Boolean(child.getText(sourceFile).trim()),
    );
    examples[title] = rootChildren.length > 1
      ? `<>\n${jsx.split('\n').map((line) => `  ${line}`).join('\n')}\n</>`
      : jsx;
  }

  ts.forEachChild(node, visit);
};

visit(sourceFile);

const generatedSource = `// Generated by scripts/generate-playground-examples.ts.\n`
  + `// Do not edit this file directly.\n`
  + `export const demoCardCodeByTitle: Record<string, string> = ${JSON.stringify(examples, null, 2)};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generatedSource);

const componentGlob = new Bun.Glob('packages/lumen-ui/src/components/**/*.{ts,tsx}');
const componentFiles: string[] = [];
for await (const file of componentGlob.scan({ cwd: projectRoot })) {
  componentFiles.push(resolve(projectRoot, file));
}

const program = ts.createProgram(componentFiles, {
  target: ts.ScriptTarget.Latest,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  jsx: ts.JsxEmit.ReactJSX,
  skipLibCheck: true,
});
const checker = program.getTypeChecker();

const propertyDescriptions: Record<string, string> = {
  active: '控制组件是否处于显示或启用状态。',
  align: '设置内容或浮层的对齐方式。',
  'aria-describedby': '关联用于补充说明组件内容的元素 ID。',
  'aria-label': '设置供辅助技术读取的名称。',
  'aria-labelledby': '关联用于命名组件的元素 ID。',
  ariaLabel: '设置组件的可访问名称。',
  as: '设置最终渲染的 HTML 元素或 React 组件。',
  checked: '受控模式下是否处于选中状态。',
  children: '组件承载的子内容。',
  className: '追加自定义 CSS 类名。',
  closeDelayMs: '设置关闭动画完成前的延迟时间，单位为毫秒。',
  closeOnEscape: '按 Escape 键时关闭浮层。',
  closeOnOverlayClick: '点击遮罩区域时关闭浮层。',
  closeOnOutsideClick: '点击浮层外部时关闭。',
  closeOnSelect: '选择项目后关闭浮层。',
  closeOnSwipe: '允许在触摸设备上沿退出方向滑动关闭抽屉。',
  contentClassName: '追加浮层内容区域的 CSS 类名。',
  defaultChecked: '非受控模式下的初始选中状态。',
  defaultOpen: '非受控模式下是否默认打开。',
  defaultValue: '非受控模式下的初始值。',
  description: '补充说明内容。',
  disabled: '禁用组件及其交互。',
  icon: '设置组件图标。',
  initialFocusRef: '浮层打开后优先聚焦的元素引用。',
  items: '定义组件渲染的数据项。',
  label: '设置可见标签或标题。',
  loading: '显示加载状态并阻止重复操作。',
  lockScroll: '浮层显示期间锁定页面滚动。',
  menuClassName: '追加菜单浮层的 CSS 类名。',
  menuMode: '启用菜单语义、焦点管理和方向键导航。',
  max: '设置允许的最大值。',
  min: '设置允许的最小值。',
  multiple: '允许选择多个值。',
  name: '设置表单控件名称。',
  finalFocusRef: '浮层关闭后恢复焦点的元素引用。',
  onRequestClose: '请求关闭浮层时触发。',
  role: '设置 dialog 或 alertdialog 无障碍语义。',
  onChange: '值发生变化时触发。',
  onClick: '点击组件时触发。',
  onOpenChange: '打开状态发生变化时触发。',
  open: '控制浮层或面板是否打开。',
  options: '定义可选择的选项。',
  placeholder: '未选择或未输入时显示的提示。',
  placement: '设置浮层或定位元素的位置。',
  required: '标记表单值为必填。',
  searchable: '启用选项搜索。',
  size: '设置组件尺寸。',
  status: '设置组件状态样式。',
  step: '设置数值变化步长。',
  style: '追加内联样式。',
  title: '设置组件标题。',
  tone: '设置内容的语义色调。',
  trigger: '渲染触发元素，并提供打开状态、菜单 ID 和开关方法。',
  value: '受控模式下的当前值。',
  variant: '设置组件的视觉变体。',
};

const getFallbackDescription = (name: string) => {
  if (propertyDescriptions[name]) return propertyDescriptions[name];
  if (name.startsWith('on')) return `组件执行 ${name.slice(2)} 对应操作时触发。`;
  if (name.startsWith('default')) return `设置 ${name.slice(7)} 的初始值。`;
  if (name.startsWith('show')) return `控制是否显示 ${name.slice(4)}。`;
  return `设置 ${name}。`;
};

const getComponentDefaults = (sourceFile: ts.SourceFile, componentName: string) => {
  const defaults: Record<string, string> = {};
  let componentNode: ts.Node | undefined;

  const findComponent = (node: ts.Node) => {
    if (
      ts.isVariableDeclaration(node)
      && ts.isIdentifier(node.name)
      && node.name.text === componentName
    ) componentNode = node.initializer;
    if (ts.isFunctionDeclaration(node) && node.name?.text === componentName) componentNode = node;
    if (!componentNode) ts.forEachChild(node, findComponent);
  };
  findComponent(sourceFile);

  const findParameters = (node: ts.Node) => {
    if (Object.keys(defaults).length || !ts.isFunctionLike(node) || !node.parameters.length) {
      ts.forEachChild(node, findParameters);
      return;
    }
    const binding = node.parameters[0]?.name;
    if (!binding || !ts.isObjectBindingPattern(binding)) return;
    for (const element of binding.elements) {
      if (!element.initializer || !ts.isIdentifier(element.name)) continue;
      defaults[element.name.text] = element.initializer.getText(sourceFile);
    }
  };
  if (componentNode) findParameters(componentNode);
  const constants = new Map<string, string>();
  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      if (ts.isIdentifier(declaration.name) && declaration.initializer) {
        constants.set(declaration.name.text, declaration.initializer.getText(sourceFile));
      }
    }
  }

  return Object.fromEntries(Object.entries(defaults).map(([name, value]) => {
    const withoutAssertion = value.replace(/\s+as\s+[A-Za-z_$][\w$]*$/, '');
    return [name, constants.get(withoutAssertion) ?? withoutAssertion];
  }));
};

type GeneratedPropDoc = {
  name: string;
  type: string;
  defaultValue: string;
  description: string;
  required: boolean;
};

const componentApi: Record<string, GeneratedPropDoc[]> = {};
for (const componentFile of componentFiles) {
  const componentSource = program.getSourceFile(componentFile);
  if (!componentSource) continue;
  const moduleSymbol = checker.getSymbolAtLocation(componentSource);
  if (!moduleSymbol) continue;

  for (const symbol of checker.getExportsOfModule(moduleSymbol)) {
    if (!symbol.name.endsWith('Props') || symbol.name === 'FormFieldRenderProps') continue;
    const componentName = symbol.name.slice(0, -5);
    const declaration = symbol.declarations?.[0];
    if (!declaration) continue;
    const propsType = checker.getDeclaredTypeOfSymbol(symbol);
    const defaults = getComponentDefaults(componentSource, componentName);
    const props = checker.getPropertiesOfType(propsType)
      .filter((property) => property.declarations?.some((item) => item.getSourceFile().fileName.startsWith(resolve(projectRoot, 'packages/lumen-ui/src/components'))))
      .map((property) => {
        const propertyDeclaration = property.valueDeclaration ?? property.declarations?.[0];
        if (!propertyDeclaration) return null;
        const documentation = ts.displayPartsToString(property.getDocumentationComment(checker));
        const propertyType = checker.getTypeOfSymbolAtLocation(property, propertyDeclaration);
        const localAlias = propertyType.aliasSymbol?.declarations?.some(
          (item) => item.getSourceFile().fileName.startsWith(resolve(projectRoot, 'packages/lumen-ui/src/components')),
        );
        return {
          name: property.name,
          type: checker.typeToString(
            propertyType,
            propertyDeclaration,
            ts.TypeFormatFlags.NoTruncation
              | (localAlias ? ts.TypeFormatFlags.InTypeAlias : 0),
          ),
          defaultValue: defaults[property.name] ?? (property.flags & ts.SymbolFlags.Optional ? 'undefined' : '-'),
          description: /[\u3400-\u9fff]/.test(documentation)
            ? documentation
            : getFallbackDescription(property.name),
          required: !(property.flags & ts.SymbolFlags.Optional),
        };
      })
      .filter((property): property is GeneratedPropDoc => Boolean(property));

    if (props.length) componentApi[componentName] = props;
  }
}

componentApi.Toast = [
  { name: 'show', type: '(message: string, type?: ToastType, options?: ToastOptions) => void', defaultValue: "type: 'info'", description: '显示指定类型的全局消息。', required: false },
  { name: 'success', type: '(message: string, options?: ToastOptions) => void', defaultValue: '-', description: '显示成功消息。', required: false },
  { name: 'info', type: '(message: string, options?: ToastOptions) => void', defaultValue: '-', description: '显示提示消息。', required: false },
  { name: 'warning', type: '(message: string, options?: ToastOptions) => void', defaultValue: '-', description: '显示警告消息。', required: false },
  { name: 'error', type: '(message: string, options?: ToastOptions) => void', defaultValue: '-', description: '显示错误消息。', required: false },
  { name: 'clear', type: '() => void', defaultValue: '-', description: '立即清除全部消息。', required: false },
  { name: 'options.duration', type: 'number', defaultValue: '2600', description: '设置消息显示时长，单位为毫秒。', required: false },
];

const generatedApiSource = `// Generated by scripts/generate-playground-examples.ts.\n`
  + `// Do not edit this file directly.\n`
  + `export type GeneratedPropDoc = { name: string; type: string; defaultValue: string; description: string; required: boolean };\n`
  + `export const generatedComponentApi: Record<string, GeneratedPropDoc[]> = ${JSON.stringify(componentApi, null, 2)};\n`;
await writeFile(apiOutputPath, generatedApiSource);
console.log(`Generated source for ${Object.keys(examples).length} cards and API for ${Object.keys(componentApi).length} components.`);
