import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import ts from 'typescript';

const projectRoot = resolve(import.meta.dirname, '..');
const sourcePath = resolve(projectRoot, 'playground/src/App.tsx');
const outputPath = resolve(projectRoot, 'playground/src/generated/demoCardCode.ts');
const sourceText = await readFile(sourcePath, 'utf8');
const sourceFile = ts.createSourceFile(
  sourcePath,
  sourceText,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TSX,
);
const examples: Record<string, string> = {};

const normalizeJsx = (source: string) => {
  const lines = source.replace(/^\s*\n|\n\s*$/g, '').split('\n');
  const continuationIndents = lines
    .slice(1)
    .filter((line) => line.trim())
    .map((line) => line.match(/^\s*/)?.[0].length ?? 0);
  const indent = continuationIndents.length ? Math.min(...continuationIndents) : 0;

  return lines
    .map((line, index) => index === 0 ? line.trimStart() : line.slice(indent))
    .join('\n');
};

const visit = (node: ts.Node) => {
  if (ts.isJsxElement(node) && node.openingElement.tagName.getText(sourceFile) === 'DemoCard') {
    const titleAttribute = node.openingElement.attributes.properties.find(
      (attribute) => ts.isJsxAttribute(attribute) && attribute.name.getText(sourceFile) === 'title',
    );
    const title = titleAttribute?.initializer && ts.isStringLiteral(titleAttribute.initializer)
      ? titleAttribute.initializer.text
      : undefined;

    if (!title) throw new Error('Every DemoCard must have a static string title.');
    if (examples[title]) throw new Error(`Duplicate DemoCard title: ${title}`);

    const jsx = normalizeJsx(
      node.children.map((child) => child.getFullText(sourceFile)).join(''),
    );
    const rootChildren = node.children.filter(
      (child) => !ts.isJsxText(child) || Boolean(child.getText(sourceFile).trim()),
    );
    examples[title] = rootChildren.length > 1
      ? `<>\n${jsx.split('\n').map((line) => `  ${line}`).join('\n')}\n</>`
      : jsx;
  }

  ts.forEachChild(node, visit);
};

visit(sourceFile);

const generatedSource = `// Generated by scripts/generate-playground-examples.ts.\n`
  + `// Do not edit this file directly.\n`
  + `export const demoCardCodeByTitle: Record<string, string> = ${JSON.stringify(examples, null, 2)};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generatedSource);
console.log(`Generated source for ${Object.keys(examples).length} playground cards.`);
